#cloud-config

write_files:
  -   path: /etc/server.conf
      owner: root:root
      permissions: "0644"
      content: |
        {
          "pg_user":  "${PG_USER}",
          "pg_password": "${PG_PASSWORD}",
          "pg_database": "${PG_DATABASE}",
          "pg_netloc": "${PG_HOSTNAME}:${PG_PORT}"
        }
runcmd:
  - [ wget, "https://s3-us-west-2.amazonaws.com/terraform-in-action/bootstrap.sh", -O, /run/bootstrap.sh ]
  - chmod 755 /run/bootstrap.sh
  - /run/bootstrap.sh
packages:
  - wget